import Head from "next/head";
import { Inter } from "next/font/google";
import SideMenu from "@/components/SideMenu";
import Header from "@/components/Header";
import DashboardHead from "@/sections/DashbroardHead";
import StatsSection from "@/sections/StatsSection";
import CountrySection from "@/sections/CountrySection";
import Footer from "@/sections/Footer";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Test Assignment</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${inter.className} dashboard-container`}>
        <SideMenu />
        <section className="dashboardArea">
          <Header />
          <section className="dashboardBodyArea">
            <DashboardHead />
            <StatsSection />
            <div style={{ display: "flex", justifyContent: "flex-end" }}>
              <div className="searchArea">
                <img src="/assets/images/icons/search.svg" alt="" />
                <input type="search" placeholder="Search" />
              </div>
            </div>

            <CountrySection />
          </section>
          <Footer />
        </section>
      </main>
    </>
  );
}
